README.md

This PR adds installation instruction for `pipenv`

📃 docs: add installation instruction for pipenv

---

.github/issue_template.md
.github/pull_request_template.md

This PR adds issue template & pull request template.

Add Issue & PR templates

---

doc/dev.md

- Adds Python code style guide to the dev doc

📃 docs: add coding style guide

---

doc/dev.md

- Adds naming convention for branch & PR

📃 docs: add branch & pr naming convention

---

doc/dev.md

- Sets PR direction branch as `develop`

📃 docs: set pr direction branch as develop

---

py_v_sdk/account.py
py_v_sdk/api.py
py_v_sdk/chain.py
py_v_sdk/contract/__init__.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/data_entry.py
py_v_sdk/tx_req.py
py_v_sdk/utils/crypto/curve_25519.py
py_v_sdk/utils/crypto/hashes/__init__.py
py_v_sdk/utils/crypto/hashes/keccak.py

- Fixes a few critical `pylint` alerts

refactor: fix critical pylint alerts

---

py_v_sdk/contract/nft_ctrt.py
py_v_sdk/data_entry.py

- Adds `send` function for NFT contract
Manually tested against the test net http://veldidina.vos.systems:9928

feat: add send function for nft contract

---

.github/pull_request_template.md

Adds test info section and checklist into the pr template
No tests required

🐳 chore: update the pr template to include checklist and test info

---

doc/dev.md

Adds philosophy section to the dev doc
No tests requried

📃 docs: add philosophy section to the dev doc

---

LICENSE

Updates the license from MIT to BSD-4
No tests required

🐳 chore: update the license to BSD-4

---

py_v_sdk/contract/nft_ctrt.py

Adds `transfer` function for nft contract
Manually tested against http://veldidina.vos.systems:9928/

✨ feat: add transfer function for nft contract

---

py_v_sdk/contract/nft_ctrt.py

Adds deposit & withdraw function for nft contract

✨ feat: add deposit & withdraw function for nft contract

---

py_v_sdk/contract/nft_ctrt.py

Adds supersede function for nft contract

✨ feat: add supersede function for nft contract

---

py_v_sdk/contract/__init__.py
py_v_sdk/contract/nft_ctrt.py

Revamps DBKey class for nft ctrt

refactor: revamp DBKey class for nft ctrt

---

py_v_sdk/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py

Adds atomic swap contract with properties & register method

✨ feat: add atomic swap contract with properties & register method

---

py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/nft_ctrt.py

Formats contract related files with black
No tests required

refactor: format contract files with black

---

README.md
py_v_sdk/__init__.py
py_v_sdk/account.py
py_v_sdk/chain.py
py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/data_entry.py
py_v_sdk/model.py
py_v_sdk/tx_req.py
py_v_sdk/utils/crypto/curve_25519.py

Adds data models.
Data models can be thought of as containers for data of specific usage with validation & basic handy methods(e.g. to b58 str)

feat: add data model

---

py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/nft_ctrt.py

Adds doc strings to package `contract`.

docs: add doc strings for contracts

---

py_v_sdk/account.py
py_v_sdk/api.py
py_v_sdk/chain.py
py_v_sdk/data_entry.py
py_v_sdk/log.py
py_v_sdk/model.py
py_v_sdk/tx_req.py

Adds as many docstrings as possible.

docs: add doc strings

---

.github/issue_template.md

Simplify the Github issue template.

chore: simplify issue template

---

py_v_sdk/account.py
py_v_sdk/api.py
py_v_sdk/model.py
py_v_sdk/tx_req.py

feat: support tx type payment

---

README.md

Update the license badge in README.md from MIT to BSD-4
No tests required.

chore: update license badge

---

README.md
py_v_sdk/api.py
py_v_sdk/contract/atomic_swap_ctrt.py
test/func_test/conftest.py
test/func_test/pytest.ini
test/func_test/test_ctrt.py

Add functional tests to NFT contract
The added test cases are run & passed locally.

test: add functional tests to NFT contract

---

README.md
test/func_test/conftest.py
test/func_test/test_acnt.py
test/func_test/test_ctrt.py

Add functional tests for method `pay` of class `Account`.
The added tests passed at local.

test: add func test for account pay

---

py_v_sdk/account.py
py_v_sdk/api.py
py_v_sdk/model.py
py_v_sdk/tx_req.py
test/func_test/conftest.py
test/func_test/test_acnt.py

Support lease & cancel leasing.
The added functional tests passed at local.

feat: support lease and lease cancel

---

README.md

Add the instruction to set up the functional test environment to README.md

docs: add test env set up instructions in readme

---

py_v_sdk/account.py
py_v_sdk/api.py
py_v_sdk/dbput.py
py_v_sdk/model.py
py_v_sdk/tx_req.py
test/func_test/test_acnt.py

Support DB Put Transaction type.
The added functional test case passed locally.

feat: support db put

---

README.md

Update the instruction in README.md to set up the functional tests envrionment.

docs: update test env setup instruction

---

README.md
doc/dev.md

Update the python version for users & devs

docs: update supported py version

---

README.md
py_v_sdk/account.py
py_v_sdk/model.py
setup.py
test/func_test/conftest.py

Unify the using & development python version to 3.9+
Functional tests passed at local.

build: unify the using & development python version to 3.9+

---

py_v_sdk/contract/tok_ctrt.py
py_v_sdk/data_entry.py
py_v_sdk/model.py

Refactor token contract.
Functional tests passed at local.

refactor: token contract

---

doc/dev.md

Update the python version for development from 3.10 to 3.9

docs: update the dev py ver from 3.10 to 3.9

---

py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/nft_ctrt.py

Add a helper function that encapsulates common logics for querying db key.
Functional tests passed locally.

refactor: encapsulate common logic for querying db key

---

py_v_sdk/contract/nft_ctrt.py

Add `tok_description` to NFT contract method `issue`.
Functional tests passed locally.

refactor: add tok_description to nft method issue

---

py_v_sdk/api.py

Supplement a few API wrappers.

feat: supplement a few api wrappers

---

py_v_sdk/api.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/tok_ctrt.py
test/func_test/test_ctrt.py

Add db querying properties and methods to token contract.
Tested manually against http://veldidina.vos.systems:9928

feat: add db querying properties and methods to token contract

---

py_v_sdk/contract/tok_ctrt.py

Slightly cleans up token contract implementation.
No tests are requried.

fix: clean up token contract

---

py_v_sdk/__init__.py
py_v_sdk/api.py
py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/contract/v_swap_ctrt.py
test/func_test/test_ctrt.py

Support V Swap contract.
Will add functional test cass.

feat: support v swap contract

---

py_v_sdk/api.py
py_v_sdk/contract/tok_ctrt.py
test/func_test/test_ctrt.py

create token contract test
it tests itself

test: create token ctrt test

---

py_v_sdk/contract/tok_ctrt.py
test/func_test/test_ctrt.py

it tests token ctrt v2 test.
It tested itself.

test: create token ctrt v2 test

---

test/func_test/conftest.py

Allow test configs to be read from env vars.
Tested locally.

test: read test config from env var

---

.github/workflows/pytest.yml
doc/dev.md

Add Github Action workflow to run tests automatically.
It is based on https://github.com/virtualeconomy/py-v-sdk/pull/61
Huge thanks to @peerchemist
Github Action was triggered in [josephzxy/py-v-sdk](https://github.com/josephzxy/py-v-sdk) and all test cases pass.
See https://github.com/josephzxy/py-v-sdk/actions/runs/1810943472

build: set up Github Action

---

README.md

Update the test environment set up instructions.

docs: update the test env set up instructions

---

.github/workflows/pytest.yml
py_v_sdk/__init__.py
py_v_sdk/contract/lock_ctrt.py
py_v_sdk/model.py
test/func_test/conftest.py
test/func_test/test_ctrt/test_lock_ctrt.py

Add lock contract
The functional test cases pass.

feat: add lock contract

---

README.md

Update the installation branch from `main` to `develop`

docs: update the installation branch from main to develop

---

py_v_sdk/api.py

Add generic get / post method for class NodeAPI
Tested manually.

feat: add generic get post method for api

---

README.md

Update the README.md
- update the supported py version from 3.9+ to 3.7+
- remove seed in example code
- add more sample code for installation from branch `main` and `develop`

docs: update py version & example code & installation methods in readme

---

py_v_sdk/api.py
py_v_sdk/chain.py

Add 2 methods to the class `Chain` to fetch blocks at a certain height or within the given range.
Tested manually.

feat: add-wrappers-for-fetching-blocks

---

py_v_sdk/contract/__init__.py

Add local token id generation
Tested manually.

feat: add local token id generation

---

py_v_sdk/contract/tok_ctrt.py

Refactor the constructor of token contract so that no unit has to be passed in.
Token contract functional tests passed locally.

feat: no need to pass unit to token contract constructor

---

py_v_sdk/contract/__init__.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/contract/tok_ctrt.py

Add base class `BaseTokCtrt` for token contract classes (NFT included)
Functional tests passed locally.

refactor: add base class for token contract(nft included)

---

py_v_sdk/api.py
py_v_sdk/contract/tok_ctrt_factory.py
py_v_sdk/data_entry.py

Add token contract(NFT included) factory so that the token contract instance will be returned when providing the token ID and the chain object.
Tested manually locally.

feat: add token contract(NFT included) factory

---

py_v_sdk/contract/lock_ctrt.py
test/func_test/test_ctrt/test_lock_ctrt.py

Clean up & refactor lock contract.
Functional test passed locally.

refactor: clean up & refactor lock ctrt

---

py_v_sdk/__init__.py
py_v_sdk/contract/__init__.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/contract/pay_chan_ctrt.py
py_v_sdk/data_entry.py
py_v_sdk/model.py
py_v_sdk/tx_req.py
py_v_sdk/utils/crypto/curve_25519.py
test/func_test/test_ctrt/test_pay_chan_ctrt.py
test/func_test/test_ctrt/test_v_swap_ctrt.py

feat: add payment channel contract

---

py_v_sdk/__init__.py
py_v_sdk/contract/sys_ctrt.py
test/func_test/test_ctrt/test_sys_ctrt.py

feat: add system contract

---

test/func_test/test_ctrt/test_nft_ctrt.py
test/func_test/test_ctrt/test_tok_ctrt.py

Fix test cases broken by atomic swap contract.

test: fix test cases broken by atomic swap ctrt

---

py_v_sdk/contract/pay_chan_ctrt.py
py_v_sdk/contract/tok_ctrt_factory.py
py_v_sdk/model.py

Include sys ctrt in tok facotry
The functional test for payment contract passed locally.

feat: include sys ctrt in tok factory

---

py_v_sdk/account.py
test/func_test/test_acnt.py
test/func_test/test_ctrt/test_sys_ctrt.py

Use `md.VSYS` as the return type of account balance.

feat: use model for account balance

---

README.md
py_v_sdk/account.py
py_v_sdk/api.py
test/func_test/test_acnt.py
test/func_test/test_ctrt/test_sys_ctrt.py

Reworks balance-related properties of class `Account`
- Use the api `/addresses/balance/details/{address}` for fetching balance
- Add property `avail_bal`
- Rename property `balance` & `effective_balance`
Related test cases passed locally.

feat: rework account balance properties

---

py_v_sdk/__init__.py
py_v_sdk/contract/tok_ctrt.py
py_v_sdk/contract/v_escrow_ctrt.py
test/func_test/conftest.py
test/func_test/test_ctrt/test_v_escrow_ctrt.py

Add V Escrow contract.
The test cases passed locally.

feat: add v escrow ctrt

---

test/func_test/test_acnt.py
test/func_test/test_api.py

Supplement type hints & doc strings of `test_api.py` & `test_acnt.py`

test: clean up test cases

---

README.md
py_v_sdk/account.py
py_v_sdk/contract/__init__.py
py_v_sdk/contract/atomic_swap_ctrt.py
py_v_sdk/contract/lock_ctrt.py
py_v_sdk/contract/nft_ctrt.py
py_v_sdk/contract/pay_chan_ctrt.py
py_v_sdk/contract/sys_ctrt.py
py_v_sdk/contract/tok_ctrt.py
py_v_sdk/contract/tok_ctrt_factory.py
py_v_sdk/contract/v_stable_swap_ctrt.py
py_v_sdk/contract/v_swap_ctrt.py
py_v_sdk/model.py
test/func_test/test_acnt.py
test/func_test/test_ctrt/test_atomic_swap_ctrt.py
test/func_test/test_ctrt/test_lock_ctrt.py
test/func_test/test_ctrt/test_nft_ctrt.py
test/func_test/test_ctrt/test_pay_chan_ctrt.py
test/func_test/test_ctrt/test_stable_swap_ctrt.py
test/func_test/test_ctrt/test_sys_ctrt.py
test/func_test/test_ctrt/test_tok_ctrt.py
test/func_test/test_ctrt/test_v_escrow_ctrt.py
test/func_test/test_ctrt/test_v_swap_ctrt.py

Refactoring codebase to use models when possible.
Cleaning & refactoring are also made along the way when see fit.

refactor: use models

---

py_v_sdk/contract/atomic_swap_ctrt.py
test/func_test/test_ctrt/test_atomic_swap_ctrt.py
test/func_test/test_ctrt/test_nft_ctrt.py
test/func_test/test_ctrt/test_tok_ctrt.py

refactor: clean up atomic swap ctrt

---

test/func_test/test_ctrt/test_atomic_swap_ctrt.py
test/func_test/test_ctrt/test_v_option_ctrt.py

Fix test cases
The fixed test cases pass.

test: fix test cases

---

README.md

Print out model in sample code in README.md 
Sample code tested locally.

docs: print out model directly

---

README.md
doc/smart_contract/lock_ctrt.md
doc/smart_contract/nft_ctrt.md
doc/smart_contract/nft_ctrt_v2.md
py_vsys/contract/__init__.py
py_vsys/contract/sys_ctrt.py
py_vsys/contract/tok_ctrt.py
test/func_test/test_ctrt/test_atomic_swap_ctrt.py
test/func_test/test_ctrt/test_lock_ctrt.py
test/func_test/test_ctrt/test_nft_ctrt.py
test/func_test/test_ctrt/test_pay_chan_ctrt.py
test/func_test/test_ctrt/test_stable_swap_ctrt.py
test/func_test/test_ctrt/test_sys_ctrt.py
test/func_test/test_ctrt/test_tok_ctrt.py
test/func_test/test_ctrt/test_v_escrow_ctrt.py
test/func_test/test_ctrt/test_v_option_ctrt.py
test/func_test/test_ctrt/test_v_swap_ctrt.py

Use `md.CtrtID` as the return type of the `ctrt_id` attribute of contract.
All test cases passed locally.

feat: wrap ctrt_id with md.CtrtID

---

README.md
doc/smart_contract/tok_ctrt_no_split.md
doc/smart_contract/tok_ctrt_no_split_v2.md
doc/smart_contract/tok_ctrt_split.md
py_vsys/contract/tok_ctrt.py

Add docs for Token Contract.
No tests required.

docs: add doc for tok ctrt

---

doc/smart_contract/pay_chan_ctrt.md
doc/smart_contract/sys_ctrt.md

add pay_chan_ctrt and sys_ctrt docs
tested on http://veldidina.vos.systems:9928/

Doc: add pay_chan_ctrt and sys_ctrt docs

---

README.md
doc/smart_contract/atomic_swap_ctrt.md

Add docs for atomic swap ctrt.

docs: add atomic swap ctrt docs

---

README.md

docs: add docs links to README

---

py_vsys/contract/v_stable_swap_ctrt.py

refactor: remove redundant print

---

py_vsys/contract/v_stable_swap_ctrt.py
test/func_test/test_ctrt/test_v_stable_swap_ctrt.py

Fix bugs in token representation in stable swap contract.
The test cases for v stable swap ctrt passed locally.

fix: fix v stable swap ctrt token representation

---

py_vsys/contract/v_stable_swap_ctrt.py

Fix the return value of price unit from `md.Token` to `int`
Related test cases passed locally.

fix: fix the return value of price unit

---

py_vsys/contract/v_stable_swap_ctrt.py

Fix v stable swap contract implementation for data type.
Related test cases passed locally.

fix: fix v stable swap contract for data type

---

py_vsys/contract/v_option_ctrt.py
py_vsys/contract/v_stable_swap_ctrt.py

Fix price unit-related logics in v stable swap contract.

fix: fix price unit in v stable swap contract

---

doc/smart_contract/v_stable_swap_ctrt.md
py_vsys/contract/v_stable_swap_ctrt.py

Add doc for v stable swap ctrt.

docs: add doc for v stable swap ctrt

---

README.md

Add links to the docs to the README
No tests required

docs: add links

---

README.md
doc/api.md
doc/chain.md
py_vsys/chain.py

docs: add doc for chain & api

---

test/func_test/test_ctrt/test_lock_ctrt.py

Fix test cases for lock ctrt.
All test cases passed locally.

test: fix test cases for lock ctrt

---

.github/workflows/pytest.yml

Fix the broken Github action CI.
The CI works on josephzxy's fork repo

build: fix ci

---

setup.py

build: bump version to 0.1.1 for uploading to pypi

---

setup.py

build: bump version to v0.1.1

---

py_vsys/contract/__init__.py
py_vsys/contract/nft_ctrt.py
py_vsys/contract/tok_ctrt.py
py_vsys/data_entry.py
py_vsys/model.py

A collection of small refactorings that includes mainly
- removing redundant codes
- logic refactoring
All functional tests passed at local.

refactor: remove redundant codes & refactoring

---

.github/workflows/pytest.yml
py_vsys/contract/atomic_swap_ctrt.py
py_vsys/contract/nft_ctrt.py
py_vsys/contract/pay_chan_ctrt.py
py_vsys/contract/v_escrow_ctrt.py
py_vsys/contract/v_option_ctrt.py
py_vsys/contract/v_stable_swap_ctrt.py
py_vsys/data_entry.py
py_vsys/model.py
test/func_test/test_ctrt/test_v_escrow_ctrt.py
test/func_test/test_ctrt/test_v_option_ctrt.py

- naming refactoring
- github action updates
- test case refactoring
Functional tests passed locally and on josephzxy/py-vsys

refactor: fixing

---

.github/workflows/pytest.yml
py_vsys/contract/atomic_swap_ctrt.py
py_vsys/contract/nft_ctrt.py
py_vsys/contract/pay_chan_ctrt.py
py_vsys/contract/v_escrow_ctrt.py
py_vsys/contract/v_option_ctrt.py
py_vsys/contract/v_stable_swap_ctrt.py
py_vsys/data_entry.py
py_vsys/model.py
setup.py
test/func_test/test_ctrt/test_v_escrow_ctrt.py
test/func_test/test_ctrt/test_v_option_ctrt.py

Release version v0.1.3
Functional tests passed both locally & on josephzxy/py-vsys

release: v0.1.3

---

setup.py

Merge branch `main` back to branch `develop` after releasing.

release: update branch develop after releasing

---

doc/account.md
py_vsys/account.py
py_vsys/contract/tok_ctrt_factory.py

Support getting token balance with an `Account` object.
Functional tests passed locally.

feat: support getting token balance with account

---

doc/smart_contract/atomic_swap_ctrt.md
doc/smart_contract/lock_ctrt.md
doc/smart_contract/pay_chan_ctrt.md
doc/smart_contract/v_escrow_ctrt.md
doc/smart_contract/v_option_ctrt.md
doc/smart_contract/v_stable_swap_ctrt.md
doc/smart_contract/v_swap_ctrt.md

Update legacy sdk name `py_v_sdk` to `py_vsys`.
No tests required.

docs: update sdk name in docs

---

setup.py

Release `v0.1.5`
No test required.

release: v0.1.5

---

py_vsys/contract/atomic_swap_ctrt.py
py_vsys/contract/nft_ctrt.py

refactor: clean up

---

py_vsys/contract/v_swap_ctrt.py

Fix typos of unit
tested with test cases

fix: fix typos of unit

---

py_vsys/contract/v_swap_ctrt.py

fix some typos.
No need to test.

fix: fix some typos

---

py_vsys/contract/atomic_swap_ctrt.py
py_vsys/contract/nft_ctrt.py
py_vsys/contract/v_stable_swap_ctrt.py

Update docs of v stable swap contract.

docs: update doc string for V stable swap contract

---

test/func_test/test_ctrt/test_atomic_swap_helper.py

update atomic helper&atomic ctrt spec
tested with pytest.

feat: update atomic helper spec

---

py_vsys/contract/atomic_swap_ctrt.py
py_vsys/contract/atomic_swap_helper.py

create atomic swap helper and update atomic swap ctrt

---

README.md
py_vsys/__init__.py
py_vsys/chain.py
py_vsys/contract/atomic_swap_helper.py
setup.py
test/func_test/conftest.py
test/func_test/test_ctrt/test_atomic_swap_ctrt.py

release the version 0.1.7
tested by pytest.

release: 0.1.7

---

py_vsys/utils/crypto/curve_25519.py

fix the problem that _acnt_seed_hash will be updated.

fix: update curve_25519

---

py_vsys/__init__.py

pv.Bytes now refers to Bytes class of model.py

fix: fix pv.Bytes reference problem

---

doc/smart_contract/nft_ctrt_v2.md

Fix function name
The new function name is aliged with other existing function name
- [/] Selected assignees
- [/] Selected reviewers (if you are not the admin of the repo)
- [/] The PR name follows [the convention](https://github.com/virtualeconomy/py-vsys/blob/develop/doc/dev.md#branch--pr-naming-convention)

docs: fix function name

---

doc/smart_contract/nft_ctrt_v2.md

Reverts virtualeconomy/py-vsys#167

Revert "docs: fix function name"

---

doc/smart_contract/nft_ctrt_v2.md

update a typo.
no need to test.

docs: update a typo

---

setup.py

Merge changes of release v0.2.1 to branch main
Functional tests passed.

release: v0.2.1
